services:
  postgres:
    image: postgres:16
    container_name: iwent-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: iwent
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d iwent"]
      interval: 5s
      timeout: 5s
      retries: 20

  # İsteğe bağlı: pgAdmin
  pgadmin:
    image: dpage/pgadmin4:8
    container_name: iwent-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  meilisearch:
    image: getmeili/meilisearch:v1.5
    container_name: iwent-meilisearch
    restart: unless-stopped
    environment:
      MEILI_MASTER_KEY: development_master_key
      MEILI_NO_ANALYTICS: true
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/meili_data

volumes:
  db_data:
  meili_data:
